#!/usr/bin/env python3
"""Write srl-evpn.yml — gnmic's configuration for streaming telemetry from srl-evpn's SR Linux nodes over gNMI — from the
lab's fabric.yml (through its renderer, tools/render.py load()). Every SR Linux node is a target (its management
address, port 57400, labelled lab / node / role / pod); the subscriptions sample BGP sessions, BFD, interfaces, Ethernet
Segments, route and MAC counts, CPU and memory every 15 s; the prometheus output (:9804) turns states into numbers
(up / established = 1, anything else 0) and shortens the names: srl_bgp_session_state{node, network_instance, peer_address}.
Run after a change to srl-evpn's fabric.yml, then ../deploy.sh. SRL_EVPN_DIR overrides where the lab is (~/srl-evpn)."""
import os, sys
from pathlib import Path
import yaml

LAB = Path(os.environ.get("SRL_EVPN_DIR", Path.home() / "srl-evpn"))
sys.path.insert(0, str(LAB / "tools"))
from render import load, SRL  # noqa: E402

SAMPLE = "15s"
SUBSCRIPTIONS = {
    "bgp": ["/network-instance[name=*]/protocols/bgp/neighbor[peer-address=*]/session-state"],
    "bfd": ["/bfd/network-instance[name=default]/peer[local-discriminator=*]/session-state"],
    "iface": ["/interface[name=*]/oper-state", "/interface[name=*]/statistics/in-octets", "/interface[name=*]/statistics/out-octets",
              "/interface[name=*]/statistics/in-error-packets", "/interface[name=*]/statistics/in-discarded-packets",
              "/interface[name=*]/statistics/out-discarded-packets"],
    "es": ["/system/network-instance/protocols/evpn/ethernet-segments/bgp-instance[id=1]/ethernet-segment[name=*]/oper-state"],
    "routes": ["/network-instance[name=*]/route-table/ipv4-unicast/statistics/active-routes"],
    "macs": ["/network-instance[name=*]/bridge-table/statistics/active-entries"],
    "system": ["/platform/control[slot=*]/cpu[index=all]/total/average-1", "/platform/control[slot=*]/memory/utilization"],
}


def config(f):
    targets = {n: {"address": f"{d['mgmt']}:57400", "event-tags": {"lab": f["lab"], "node": n, "role": d["role"], "pod": str(d.get("pod") or "")}}
               for n, d in f["nodes"].items() if d["role"] in SRL}
    return {
        "username": "admin", "password": "NokiaSrl1!", "skip-verify": True, "encoding": "json_ietf", "log": True,
        "targets": targets,
        "subscriptions": {k: {"paths": v, "mode": "stream", "stream-mode": "sample", "sample-interval": SAMPLE} for k, v in SUBSCRIPTIONS.items()},
        "processors": {
            "short-names": {"event-strings": {"value-names": [".*"], "transforms": [{"path-base": {"apply-on": "name"}}]}},
            "states": {"event-strings": {"value-names": [".*state$"], "transforms": [
                {"replace": {"apply-on": "value", "old": "^(up|UP|established)$", "new": "1"}},
                {"replace": {"apply-on": "value", "old": "^[A-Za-z][A-Za-z_-]*$", "new": "0"}}]}},
            "numbers": {"event-convert": {"value-names": [".*"], "type": "float"}},
        },
        "outputs": {"prom": {"type": "prometheus", "listen": ":9804", "path": "/metrics", "metric-prefix": "srl",
                             "append-subscription-name": True, "export-timestamps": False, "expiration": "60s",
                             "event-processors": ["short-names", "states", "numbers"]}},
    }


def main():
    out = Path(__file__).with_name("srl-evpn.yml")
    out.write_text(f"# Generated by gen_srl_evpn.py from {LAB}/fabric.yml — do not edit\n" + yaml.safe_dump(config(load()), sort_keys=False, width=200))
    print("wrote", out.name)


if __name__ == "__main__":
    main()
