#!/usr/bin/env python3
"""Write evpn-clab-names.lua (the names evpn-clab.lua gives its flow records) from the lab's fabric.yml, through the lab's
own renderer (`tools/render.py flow-names`). Run after a change to evpn-clab's fabric.yml, then ../deploy.sh.
EVPN_CLAB_DIR overrides where the lab is (default ~/evpn-clab)."""
import json, os, subprocess, sys
from pathlib import Path

LAB = Path(os.environ.get("EVPN_CLAB_DIR", Path.home() / "evpn-clab"))


def lua(v, indent=1):
    pad = " " * indent
    if isinstance(v, dict):
        if not v: return "{}"
        items = [f"{pad}[{lua(k) if isinstance(k, int) else json.dumps(k)}] = {lua(x, indent + 1)}" for k, x in v.items()]
        return "{\n" + ",\n".join(items) + "\n" + " " * (indent - 1) + "}"
    if isinstance(v, list): return "{" + ", ".join(lua(x, indent + 1) for x in v) + "}"
    if v is None: return "nil"
    if isinstance(v, bool): return "true" if v else "false"
    return json.dumps(v)


def main():
    n = json.loads(subprocess.run([sys.executable, str(LAB / "tools/render.py"), "flow-names"], check=True, capture_output=True, text=True).stdout)
    n["vnis"] = {int(k): v for k, v in n["vnis"].items()}
    n["edge_vlans"] = {int(k): v for k, v in n["edge_vlans"].items()}
    out = Path(__file__).with_name("evpn-clab-names.lua")
    out.write_text(f"-- Generated by gen_evpn_clab.py from {LAB}/fabric.yml — do not edit\nreturn {lua(n)}\n")
    print("wrote", out.name)


if __name__ == "__main__":
    main()
